"""
Used to validate chat data fields before pushing them into the database
"""

from pydantic import BaseModel, Field 
# Schema kiểm duyệt dữ liệu ĐẦU VÀO (Frontend -> Backend)
class ChatRequest(BaseModel):
    subject: str = Field(..., description="The unique system identifier for the subject in lowercase snake_case (e.g., 'giai_tich_1', 'triet_hoc_maclenin')")
    chapter: str = Field(..., description="The unique identifier for the specific chapter or learning module. Use lowercase snake_case to match data file naming conventions (e.g., 'chuong_1', 'bai_hoc_2')")
    # tránh rỗng khi đưa vào dtb
    message: str = Field(..., min_length=1, description="The actual query or question provided by the student")

# Schema định dạng dữ liệu ĐẦU RA (Backend -> Frontend)
class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response or explanation generated by the AI Tutor")
    status: str = Field(default="success", description="The execution status of the chat request processing")