events {
    worker_connections 1024;
}

http {
    client_max_body_size 100M;
    
    server {
        listen 80;
        server_name api.ptitaitutor.com ptitaitutor.com www.ptitaitutor.com;

        location / {
            proxy_pass http://spring-api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name ai.ptitaitutor.com;

        location / {
            proxy_pass http://ai-api:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
